server:
  port: 9090

spring:
  application:
    name: batch-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/drinkly?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: INFO

# Feign Client Timeout ??
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
